name: postit

services:
  app:
    container_name: app
    image: gperdrizet/postit-app
    environment:
      HF_HOME: /data
      FLASK_IP: model
      FLASK_PORT: $FLASK_PORT
    command: python postit.py

  model:
    container_name: model
    image: gperdrizet/postit-model
    volumes:
      - $HF_HOME:/data
    environment:
      HF_HOME: /data
      FLASK_IP: $FLASK_IP
      FLASK_PORT: $FLASK_PORT
      REDIS_IP: 'redis'
      REDIS_PORT: $REDIS_PORT
      HF_TOKEN: $HF_TOKEN
      REDIS_PASSWORD: $REDIS_PASSWORD
    ports:
      - $FLASK_PORT:$FLASK_PORT 
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['1']
            capabilities: [gpu]
    command: ./start_model.sh

  redis:
    container_name: redis
    image: gperdrizet/postit-redis
    environment:
      REDIS_IP: $REDIS_IP
      REDIS_PORT: $REDIS_PORT
      REDIS_PASSWORD: $REDIS_PASSWORD
    ports:
      - '$REDIS_PORT:$REDIS_PORT'
    command: ./start_server.sh
    privileged: true